### ISSUE TITLE
Electrical rules check failed: EuroRack header & LT1251

### ISSUE THREAD

**Issue by macumbista** [joem/jwm_kicad_symbols_misc#1]
Hi Joe, it's entirely possible I am not using these symbols correctly, but in the electrical rules check I get a string of errors from two of your parts. 

Most are from the EuroRack header, of a few types. The first type is "a pin with a 'no connection' flag is connected" (pins 11, 13, 15) since I have these pins marked with no connection, however they are internally connected to other header pins. The second type is "pins of type Output and Output are connected" (basically all the +V pins connected, all the GND pins connected, and all the -V pins connected).

The last errors are for the LT1251, which assumes that 10 and 12 are power pins.

Any suggestions how to correct these errors would be greatly appreciated. Thank you for your contributions to the community! Derek

**Comment by joem** [comment]
You're definitely right. I made these before I ever knew about ERC, and since then I've realized they had issues. I had been ignoring the ERC issues with these specific parts on my own designs, but this is as good a reason as any to finally fix things, which I think I've done in 0839c7fc359c387db2579730f0b8ea9de7e9567c and 572a19bc537f88f2e8e2e9614a7eb44701ef9273.

I fixed the **Eurorack_Header_LZX** by making the invisible pins be passive. This means you won't get the "two outputs connected together" errors. That said, _if you use a NC flag on some of the pins (like if you're not planning to connect the CV or Gate pins to anything), you'll still get a warning from the ERC_. This is due to the fact that the visible pins are already connected to the invisible pins they're stacked on top of, so using a NC flag is kind of weird since you're saying NC but also connecting them. It's just a warning, though, so you can ignore it. Or for NC, don't use the NC flag and just leave nothing on those pins.

I think in the future I might make a few different variations of this symbol where some pins are permanently set as NC pins in the symbol. For instance, I think it could make sense to have a variation where the CV, Gate and +5V are all set to NC pins. That's the most elegant solution I could come up with to this NC issue.

I also made the power pins be power outputs (instead of just outputs), since this seems like the right thing to do. It'll hopefully get rid of any warning or errors that pop up due to power inputs not being driven, if connected directly to a power input (which usually isn't the case for eurorack, so it kind of doesn't matter).

For reference as to what to do with stacked pins, I followed these two: https://klc.kicad.org/symbol/s4/s4.3/ and https://forum.kicad.info/t/electrical-type-of-schematic-symbol-pins-kicad-4-and-kicad-5/9439

**Comment by joem** [comment]
As for the **LT1251_LZX**, I'm a little less clear about what to do. I'm not kicad pro myself, so I referred again to the above linked references and the LT1251 datasheet, and as best as I can tell, the only thing that needed changing on this symbol was making pin 12 (VFS) not be a power input but just a normal input so it matches pin 3 (VC). You mentioned pin 10 being an issue, and I almost convinced myself it should be a power input since it's often connected to GND, but the datasheet mentioned the possibility of grounding pin 3 and then using pin 5 as the control voltage input, and it seems like the same should be possible with pins 12 and 10. Based on that I'm fairly certain that pin 10 is correct as an input and not a power input.

I've committed that one change (change pin 12 to input instead of power input) to this symbol and the other changes to the other sybol and closed this issue. Hopefully these changes fix things for you. If not, let me know. I think we can still discuss an issue after it's closed, or maybe reopen the issue to keep talking. I'm only an amateur at kicad and electronics design, so it's entirely possible I didn't fix things the way they actually should have been fixed.  :)
